Fix error in 1.10.3 with KubernetesExecutor
When a pod is created to run a tasks, a volume is mounted on
/usr/local/airflow/airflow/dags for the dags and the parent directory is
created as `root`, thus making the directory non-writable.

```python
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 38, in <module>
    from airflow import settings, configuration as conf
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 36, in <module>
    from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
  File "/usr/local/lib/python3.6/site-packages/airflow/configuration.py", line 541, in <module>
    with open(TEST_CONFIG_FILE, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/airflow/unittests.cfg'
```

This patch creates the directory ahead, before the home directory
ownership is changed